version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../..:/var/www/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-airport_lounges}
      - DB_USERNAME=${DB_USER:-develop}
      - DB_PASSWORD=${DB_PASS:-secret}
    depends_on:
      - mail

  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-airport_lounges}
      - MYSQL_USER=${DB_USER:-develop}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

  redis:
    image: redis:6.0.8
    ports:
      - ${REDIS_PORT:-6379}:6379

  mail:
    image: mailhog/mailhog
    ports:
      - ${SMTP_PORT:-8025}:8025
