version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../..:/var/www/app
    depends_on:
      - mail

  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d 
    environment:
      - MYSQL_DATABASE=${DB_NAME:-airport_lounges}
      - MYSQL_USER=${DB_USER:-develop}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=develop
      - PMA_PASSWORD=secret
    links:
      - db
    ports:
      - ${DB_PORT:-81}:81
    volumes:
      - /sessions

  redis:
    image: redis:6.0.8
    ports:
      - ${REDIS_PORT:-6379}:6379

  mail:
    image: mailhog/mailhog
    ports:
      - ${SMTP_PORT:-8025}:8025
