# This is a basic workflow to help you get started with Actions

name: Laravel CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [master, deploy]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: composer install

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix ./app

      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply php-cs-fixer changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  phpunit:
    needs: [php-cs-fixer]
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: airport_lounges_test
          MYSQL_ROOT_PASSWORD: secret
          TZ: UTC
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0.3'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install composer dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
        php artisan migrate:refresh --seed
    - name: Run Testsuite
      run: php artisan test